version: '2'

services:
    # InfluxDB service
    influxdb:
        image: influxdb
        volumes:
            - ./data/influxdb:/var/lib/influxdb
        ports:
            - "8086:8086"
        environment:
            INFLUXDB_DB: urlshortener
#            INFLUXDB_ADMIN_USER: admin
#            INFLUXDB_ADMIN_PASSWORD: admin
#            INFLUXDB_HTTP_AUTH_ENABLED: "true"

    # Kapacitor service
    kapacitor:
        image: kapacitor
        environment:
            KAPACITOR_HOSTNAME: kapacitor
            KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
        volumes:
            - ./data/kapacitor:/var/lib/kapacitor
        links:
            - influxdb
        ports:
            - "9092:9092"

    # Telegraf service
    telegraf:
        image: telegraf
        volumes:
            - ./etc/rsyslog.conf:/etc/rsyslog.conf
            - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        links:
            - influxdb
        ports:
            - "8092:8092/udp"
            - "8094:8094"
            - "8125:8125/udp"

    # Chronograf service
    chronograf:
        image: quay.io/influxdb/chronograf
        volumes:
            - ./data/chronograf:/var/lib/chronograf
        ports:
            - "8888:8888"
        links:
            - influxdb

    # service for influx CLI tool.
    # docker-compose run influxdb-cli
    influxdb-cli:
        image: influxdb
        entrypoint:
            - influx
            - host
            - influxdb
        links:
            - influxdb

    # service for kapacitor CLI tool.
    # docker-compose run kapacitor-cli
    kapacitor-cli:
        image: kapacitor
        entrypoint: bash
        environment:
            KAPACITOR_URL: http://kapacitor:9092
        links:
            - kapacitor

    # converter storage
    redis:
        image: redis
        volumes:
            - ./data/redis:/data
        ports:
            - "6379:6379"

    # converter service
    url-converter:
        image: smoczyna/url-converter
        ports:
            - "8080:8080"
        links:
            - influxdb
            - redis
